/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI example
 * OpenAPI example API docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ExampleRequest
 */
export interface ExampleRequest {
    /**
     * 
     * @type {string}
     * @memberof ExampleRequest
     */
    'stringAttribute': string;
    /**
     * 
     * @type {Date}
     * @memberof ExampleRequest
     */
    'dateAttribute': Date;
}
/**
 * 
 * @export
 * @interface ExampleResponse
 */
export interface ExampleResponse {
    /**
     * 
     * @type {string}
     * @memberof ExampleResponse
     */
    'stringAttribute': string;
    /**
     * 
     * @type {Date}
     * @memberof ExampleResponse
     */
    'dateAttribute': Date;
}

/**
 * AppApi - axios parameter creator
 * @export
 */
export const AppApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ExampleRequest} exampleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        example: async (exampleRequest: ExampleRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'exampleRequest' is not null or undefined
            assertParamExists('example', 'exampleRequest', exampleRequest)
            const localVarPath = `/api/app/example`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(exampleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppApi - functional programming interface
 * @export
 */
export const AppApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ExampleRequest} exampleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async example(exampleRequest: ExampleRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExampleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.example(exampleRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AppApi - factory interface
 * @export
 */
export const AppApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppApiFp(configuration)
    return {
        /**
         * 
         * @param {ExampleRequest} exampleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        example(exampleRequest: ExampleRequest, options?: any): AxiosPromise<ExampleResponse> {
            return localVarFp.example(exampleRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppApi - object-oriented interface
 * @export
 * @class AppApi
 * @extends {BaseAPI}
 */
export class AppApi extends BaseAPI {
    /**
     * 
     * @param {ExampleRequest} exampleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public example(exampleRequest: ExampleRequest, options?: AxiosRequestConfig) {
        return AppApiFp(this.configuration).example(exampleRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


